name: Build AzerothCore

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variable for valanior-source
      run: |
        echo "VALANIOR_SOURCE=/valanior-source" >> $GITHUB_ENV

    - name: Debug - List valanior-source directory
      run: |
        echo "Listing \$VALANIOR_SOURCE directory:"
        ls -la $VALANIOR_SOURCE

    - name: Ensure directory for repo2 exists and pull latest sources
      run: |
        if [ -d "$VALANIOR_SOURCE/build-valanior/bin" ]; then
          echo "Directory $VALANIOR_SOURCE/build-valanior/bin exists."
          cd $VALANIOR_SOURCE/build-valanior/bin
          echo "Current directory: $(pwd)"
          echo "Listing files:"
          ls -la
          git pull origin master
        else
          echo "Directory $VALANIOR_SOURCE/build-valanior/bin does not exist. Exiting."
          exit 1
        fi

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Build AzerothCore
      run: |
        cd $VALANIOR_SOURCE/build-valanior/bin
        mkdir -p build
        cd build
        cmake ../
        make -j $(nproc)
