name: Build AzerothCore

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull latest sources from main repo
      run: git pull origin main

    - name: Pull latest sources from additional repo 1 with root privileges
      run: |
        cd /valanior-source/build/build-valanior
      	sudo git pull origin master

    - name: Ensure directory for repo2 exists and pull latest sources
      run: |
        mkdir -p /path/to/repo2
        cd /path/to/repo2
        git pull origin master

    - name: Install dependencies
      run: |
        sudo apt-get update

    - name: Build AzerothCore
      run: |
        mkdir build
        cd build
        cmake ../
        make -j $(nproc)


