name: Update and Build Valanior Source

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make script executable and run
        run: |
          ./update_and_build.sh
        shell: bash
