name: Build Valanior Source

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout valanior-source repository
        uses: actions/checkout@v2

      - name: Pull latest sources from main repo
        run: git pull origin main

      - name: Install dependencies
        run: |
          sudo apt update

      - name: Pull latest changes in dbc
        run: |
          cd build-valanior/bin/dbc
          git pull origin master
          cd ../../../..
        shell: bash