name: Update and Build Valanior Source

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout valanior-source repository
        run: |
          cd /valanior-source/
          git pull origin main
        shell: bash

      - name: Checkout dbc repository
        run: |
          cd /azeroth-server/bin/dbc/
          git pull origin master
        shell: bash